sudo: false

# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

## после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
## Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

